Vessels/urls.py
# Load path from django.urls
from django.urls import path

# Load this applications views.py file
from . import views

# define url patterns
urlpatterns = [
    # get index view
    # example url : /airports/
    path('', views.index),
    # show airport info
    # example url /airports/MYR
    # notice the airport_code parameter in the url matches
    # the parameter in the airport_info function
    path('Vessels/', views.Vessels),
    path('/<str:vessel_name>', views.Vessel_info),
    path('Vessels/Charleston', views.charleston_vessels),
    path('Vessels/<int:vessel_id>/', views.vessel_schedule),
    path('Port/', views.port_info),
]

csci409fp/urls.py
from django.contrib import admin
from django.urls import include, path

import Vessels.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Vessels.urls')),
]

Vessels/models.py
from django.db import models

# Create your models here.


class Vessel(models.Model):
    vessel_name = models.CharField(max_length=200)

    def __str__(self):
        return self.vessel_name


class VesselSchedule(models.Model):
    vessel = models.ForeignKey(Vessel, on_delete=models.RESTRICT)
    voyage_number = models.CharField(max_length=50)

    def __str__(self):
        return self.vessel.vessel_name + "- " + self.voyage_number


class PortCall(models.Model):
    vessel_schedule = models.ForeignKey(VesselSchedule, on_delete=models.RESTRICT)
    port = models.CharField(max_length=200)
    port_country = models.CharField(max_length=2)
    arrival = models.DateTimeField()
    departure = models.DateTimeField()

Vessels/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Vessel, VesselSchedule, PortCall
from django.shortcuts import render
# Create your views here.


def index(request):
    return render(request, 'Vessels/base.html')


def Vessels(request):
    vessels = Vessel.objects.all()
    context = {'vessels': vessels}
    return render(request, 'Vessels/Vessels.html', context)


#def index(request):
    #return HttpResponse('Hello from Vessels');


def Vessel_info(request, vessel_name):
    return HttpResponse('Showing info for vessel ' + vessel_name);


def port_info(request):
    ports = PortCall.objects.all()
    port_list = ', '.join([p.port for p in ports])
    return HttpResponse('Here is a list of our ports: ' + port_list);


# MIGHT BE AWFUL
def charleston_vessels(request):
    port_calls = PortCall.objects.filter(port='Charleston')
    vessels = set([port_call.vessel_schedule.vessel for port_call in port_calls])
    return render(request, 'Vessels/Charleston.html', {'vessels': vessels})


def vessel_schedule(request, vessel_id):
    vessel = Vessel.objects.get(id=vessel_id)
    schedules = VesselSchedule.objects.filter(vessel=vessel)
    context = {
        'vessel': vessel,
        'schedules': schedules,
    }
    return render(request, 'Vessels/vessel_schedule.html', context)

Vessels/templates/Vessels/Charleston.html
{% block content %}
<h1>Vessels coming into Charleston</h1>
<ul>
{% for vessel in vessels %}
    <li>{{ vessel.vessel_name }}</li>
{% endfor %}
</ul>
{% endblock %}

Vessels/templates/Vessels/Vessels.html
{% block content %}
    <h1>Vessels</h1>
    <table class="table table-striped table-bordered">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Vessel Names:</th>
            </tr>
        </thead>
        <tbody>
            {% for vessel in vessels %}
                <tr>
                    <td>{{ vessel.vessel_name }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

Vessels/templates/Vessels/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">CSCI 409</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/Vessels">Vessels</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/shipments">Shipments</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<main>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</main>
</body>
</html>

Vessels/templates/Vessels/index.html
<h1> HELLO THIS IS MY HOME SCREEN</h1>

Vessels/templates/Vessels/vessel_schedule.html
{% block content %}
  <h1>{{ vessel.vessel_name }} Schedule</h1>
  <p><strong>Departing from:</strong> {{ schedules.first.portcall_set.first.port }}</p>
  <p><strong>Destination:</strong> {{ schedules.last.portcall_set.last.port }}</p>
  <hr>
  <table>
    <thead>
      <tr>
        <th>Voyage Number</th>
        <th>Port</th>
        <th>Port Country</th>
        <th>Arrival</th>
        <th>Departure</th>
      </tr>
    </thead>
    <tbody>
      {% for schedule in schedules %}
        {% for portcall in schedule.portcall_set.all %}
          <tr>
            {% if forloop.first %}
              <td rowspan="{{ schedule.portcall_set.count }}">{{ schedule.voyage_number }}</td>
            {% endif %}
            <td>{{ portcall.port }}</td>
            <td>{{ portcall.port_country }}</td>
            <td>{{ portcall.arrival }}</td>
            <td>{{ portcall.departure }}</td>
          </tr>
        {% endfor %}
      {% endfor %}
    </tbody>
  </table>
{% endblock %}